<a href="https://colab.research.google.com/github/sagar181203/ResoluteAI_Software_Internship/blob/main/task2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("Hello World!!!")

Hello World!!!


Data Types

In [ ]:
# 1.Numeric 

#integer
n=12
print(type(n))

#Float
f=78.3
print(type(f))

#Complex
c=2+3j
print(type(c))

#boolean 
b=f<n
print(type(b))

# 2.List
l=[1,2,3,4,5]
print(type(l))

# 3.Tupple
t=(1,2,3,4,5)
print(type(t))

# 4.set
s={1,2,3,4,5}
print(type(s))

# 5.Dictonary
D={1:'Sagar',2:'kumar',3:'Aiml'}
print(type(D))

<class 'int'>
<class 'float'>
<class 'complex'>
<class 'bool'>
<class 'list'>
<class 'tuple'>
<class 'set'>
<class 'dict'>


Operators

In [ ]:
# Arithmetic operators
a,b=5,6
print(a+b)
print(a-b)
print(a*b)
print(a/b)

# Assignment operator
a,b=5,6
a += 1
print(a)
b-=1
print(b)

#Unary Operator
n=9
n=-n
print(n)

# Relational Operator  
a,b=5,6
print(a==b)
print(a>b)
print(a<b)
print(a!=b)

# Logical operator
a,b=5,6
a<8 and b<9
a<8 or b<9

11
-1
30
0.8333333333333334
6
5
-9
False
False
True
True


True

Number system conversion

In [ ]:
# To Binary (0-1)
print(bin(34))

# To octal (0-7)
print(oct(34))

# To Hex Decimal (0-9 a-f)
print(hex(34))

0b100010
0o42
0x22


Bitwise Operator

In [ ]:
# tilde
print(~8)

-9


In [ ]:
#Bitwise And
8 & 9
 

8

In [ ]:
#Bitwise or
8|9

9

In [ ]:
#Bitwise Xor
8^9

1

In [ ]:
# Left Shift
8<<2

32

In [ ]:
# Left Shift
8>>2

2

User Input

In [ ]:
# Direct input through the assignment operator
a=9
b=8
print(a+b)

17


In [ ]:
# User input for the integer
a=int(input("Enter the  1st number:"))
b=int(input("Enter the  2nd number:"))
print("sum is ",a+b)

Enter the  1st number:12
Enter the  2nd number:6
sum is  18


In [ ]:
# User input for the String
str=input("Enter the Name:")
print(str)

result=eval(input("Expression:"))
print(result)

Enter the Name:sagar
sagar
Expression:2+3-1
4


**List**

In [ ]:
# list having numbers
list=[1,2,3,4,5]
print(list)
print(list[0]) # with range 
print(list[4])

# List having string
name=['sagar','kumar','Aiml']
print(name)

# list having different data types
l=[35,'sagar',5.5]
print(l)

# list having lists 
m=[list,name]
print(m)

#list are mutable so we can perform such operation like--

# append
l.append(76)
print("After append -",l)

# pop
l.pop() 
print("After pop -",l)

# reverse
l.reverse()  #we can do for count(), copy(),index(), insert(),clear() etc
print("After reverse -",l)

[1, 2, 3, 4, 5]
1
5
['sagar', 'kumar', 'Aiml']
[35, 'sagar', 5.5]
[[1, 2, 3, 4, 5], ['sagar', 'kumar', 'Aiml']]
After append - [35, 'sagar', 5.5, 76]
After pop - [35, 'sagar', 5.5]
After reverse - [5.5, 'sagar', 35]


In [ ]:
# some functions 
list=[17,2,83,48,15] 
list.sort()                                    # sort
print("Sorted list",list)
print("Minimum in list :",min(list))           # min
print("Max in list :",max(list))               # max
print("Sum of list elements  :",sum(list))     # sum                         

Sorted list [2, 15, 17, 48, 83]
Minimum in list : 2
Max in list : 83
Sum of list elements  : 165


**Tuple** **and** **Set**

In [ ]:
# tuples are immutable
tup=(12,34,12,55)
print(tup)


# set will fetch the element without sequence 
s={22,45,667,78,45}
print(s)  #index will not support and duplicate value


(12, 34, 12, 55)
{667, 45, 78, 22}


**Dictionary**

In [ ]:
# acessing the dict from the indexing 
d={1:'Sagar',2:'kumar',3:'Aiml'}
print(d)
print(d.get(1))

# dictionary with the help of list ( merging )
no=[1,2,3]                              # also can be done by the set
name=['sagar','kumar','aiml']
info=dict(zip(no,name))
print(info)

# extending Or adding 
info[4]='4th_sem'
print("After extending:",info)

# deleting from dict 
del info[4]
print("After delete:",info)


{1: 'Sagar', 2: 'kumar', 3: 'Aiml'}
Sagar
{1: 'sagar', 2: 'kumar', 3: 'aiml'}
After extending: {1: 'sagar', 2: 'kumar', 3: 'aiml', 4: '4th_sem'}
After delete: {1: 'sagar', 2: 'kumar', 3: 'aiml'}


**Conditioning**

In [ ]:
# condition to check odd or even
n=int(input ("Enter the number :")) 
r=n%2
if r==0:
  print("Even Number")
else:
    print("Odd Number")      

Enter the number :88
Even Number


In [ ]:
# conditioning statement if ,elif, else
hour =int (input ("Enter the hour in military time :"))
if hour < 12:
    greeting = "Good morning"
elif hour < 18:
    greeting = "Good afternoon"
else:
    greeting = "Good night"
print(greeting)

Enter the hour in military time :23
Good night


**While** **Loop**

In [ ]:
i=1 #initialize
while i<=5: # condition
    print("Artificial Intelligence")
    i+=1 # Either Incrementation or Decrementation 

Artificial Intelligence
Artificial Intelligence
Artificial Intelligence
Artificial Intelligence
Artificial Intelligence


**For** **Loop**

In [ ]:
# for loop with Range (start,final,step)
for i in range (1,10,1):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [ ]:
# with char
name ="sagar"
for char in name:
    print(char)
print("\n")

# with  num
for num in range(5):
      print(num)       

s
a
g
a
r


0
1
2
3
4


**Break, Continue, Pass**

In [ ]:
# Break
for i in range (10):
    if i==4:
        break
    print(i)    
print("\n")

# continue
for i in range (10):
    if i==4:
        continue
    print(i)    
print("\n")

# Pass
for i in range (10):
    if i==4:
        pass
    print(i)    

0
1
2
3


0
1
2
3
5
6
7
8
9


0
1
2
3
4
5
6
7
8
9


**For** **Else** 

In [ ]:
n=[65,23,45,67]
for num in n:
    if num%2==0:
      print(num)
      break
else:
    print("Not there in list")      

Not there in list


**Array**

In [ ]:
# all data will be same type
from array import*
                                        # i for signed int
value=array('i',[88, -787 , 99, 55])    # I for unsigned int 
print(value)

# buffer_ info to get Size of array

print(value.buffer_info()) #(address, size)

# reverse of array
value.reverse()
print(value)
print(value[2]) # Access with index
print("\n")


# for loop
for i in range (4):
    print(value[i])
print("\n")

# With typecode 
new=array(value.typecode,( a for a in value ))
for i in new:
    print(i)

array('i', [88, -787, 99, 55])
(139890510806400, 4)
array('i', [55, 99, -787, 88])
-787


55
99
-787
88


55
99
-787
88


In [ ]:
# taking  User input to create an array 
from array import *
a=array('i',[])
n= int (input ("Enter the array length:")) 
for i in range (n):
    x= int (input ("Enter the element:")) 
    a.append(x)
print(a)
print("\n")    

# Searching the value
value= int (input ("Enter the element for search:"))
k=0
for i in a:
    if i==value:
      break
    k+=1
print("Element found at index  :",a.index(value))

Enter the array length:5
Enter the element:1
Enter the element:2
Enter the element:3
Enter the element:4
Enter the element:5
array('i', [1, 2, 3, 4, 5])


Enter the element for search:3
Element found at index  : 2


In [ ]:
# numpy for Array

from numpy import*
A=array([1,2,3,4,5,6,7,8])
print(A)

[1 2 3 4 5 6 7 8]


In [ ]:
# different way to create array
from numpy import*
# 1 array()
a=array([1,2,3,4,5,6,7,8])
print(a)

# 2 linspace  (start, stop, no. of parts)
b=linspace(0,10,11)
print(b)

# 3 arange  (start, stop, steps)
c=arange(0,10,2)
print(c)

# 4 logspace  (start, stop, no. of parts)
d=linspace(0,10,3)
print(d)

# 5 Zeros()
e=zeros(5)
print(e)

# 6  ones()
f=ones(5)
print(f)



[1 2 3 4 5 6 7 8]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[0 2 4 6 8]
[ 0.  5. 10.]
[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]


In [ ]:
from numpy import*
arr=array([1,2,3,4,5])
arr+=5
print(arr)

# Addition of two Array
arr1=array([1,2,3,4,5])
arr2=array([6,7,8,9,1])
arr3=arr1+arr2
print("After Addition new array",arr3)


print(sin(arr)) #like same for cos,tan,log,sum,min,max ,sqrt etc

# concatination
print(concatenate([arr1,arr2]))

# copying of array
t1=array([1,3,4,5,6])
t2=t1  # WITH same add.
print(t2)

# with new Address
t3=t1.view()
print(t3)

print("Address of t1",id(t1))
print("Address of t2",id(t2))
print("Address of t3",id(t3))



[ 6  7  8  9 10]
After Addition new array [ 7  9 11 13  6]
[-0.2794155   0.6569866   0.98935825  0.41211849 -0.54402111]
[1 2 3 4 5 6 7 8 9 1]
[1 3 4 5 6]
[1 3 4 5 6]
Address of t1 139889228926672
Address of t2 139889228926672
Address of t3 139889228927728


**Multi** **Dimension** **Array**

In [ ]:
# Multi Dimension Array
from numpy import*
a=array([[1,2,3],[4,5,6]])
print(a)

# oprations
print("Size:",a.size) #size of entire block
print("Dimension:",a.ndim) # dimension
print("Type",a.dtype) # type
print("Type",a.shape) # no. of row and column

# reshape or conversion of dimension
ar=array([[1,2,3],[4,5,6]])
ar2=ar.flatten()                        # multi to 1D
print("2D to 1D",ar2)\

s=array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
ar3=s.reshape(3,4)                       # 1D to 2D
print("1D to 2D",ar3)

[[1 2 3]
 [4 5 6]]
Size: 6
Dimension: 2
Type int64
Type (2, 3)
2D to 1D [1 2 3 4 5 6]
1D to 2D [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


**Matrix**

In [ ]:
# matrix
from numpy import*

m=matrix('1 2 3 ; 4 5 6; 7 8 9 ')
print(m)

# matrix from the array
a=array([[1,2,3],[4,5,6]])
n=matrix(a)
print(n)

# operation
print(m.max())
print(m.min())

# Addition and multiplication
m1=matrix('1 2 3 ; 4 5 6; 7 8 9 ')
m2=matrix('5 7 2 ; 8 1 3;  4 9 6 ')

m3=m1+m2
m4=m1*m2
print("Addition of matrix :\n",m3)
print("multiplication of matrix :\n",m4)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]]
9
1
Addition of matrix :
 [[ 6  9  5]
 [12  6  9]
 [11 17 15]]
multiplication of matrix :
 [[ 33  36  26]
 [ 84  87  59]
 [135 138  92]]


**Function**

In [ ]:
def add(a,b): # format Parameter
 c=a+b
 return c
print(add(56,4)) # actual parameter also for  position

#deafult parameter
def add(a,b=2):
 c=a+b
 return c
print(add(56)) 

#keyword parameter
def stu(name,age):
  print(name)
  print(age)


print(stu(age=20,name='sagar')) 




60
58
sagar
20
None


In [ ]:
# keyword variable length parameter
def stu(name,**data):
  print(name) 
  print(data)

stu('sagar',age=20, branch='AIML')



def stud(name,**data):
  print(name) 
  
  for i,j in data.items():
    print(i,j)
stud('sagar',age=20, branch='AIML')

sagar
{'age': 20, 'branch': 'AIML'}
sagar
age 20
branch AIML


In [ ]:
#global veriable
a=99
def new():
  a=90  # local variable
  print("local:",a)
new()
print("Global:",a)  

local: 90
Global: 99


In [ ]:
#count
def count(lst):
      even=0
      odd=0
      for i in lst:
        if i%2==0:
          even+=1
        else:
          odd+=1
      return even,odd

lst=[12,34,56,35,45,88]
even,odd=count(lst )
print("Even:{} and odd :{}".format(even,odd))


Even:4 and odd :2


In [ ]:
# Recursion
def fact(n):
  f=1
  for i in range(1,n+1):
      f=f*i
  return f

n=int(input("Enter the Number:")) 
factorial=fact(n)
print(factorial)


Enter the Number:4
24


**Lambda**

In [ ]:
f=lambda a:a*a
r=f(25)
print(r)

625


**filter**, **map**, **reduce**

In [ ]:
# filter

num=[1,2,3,4,5,8,9]
check=list(filter(lambda n: n%2==0,num)) # using lambda for checking the even number

print(check)


[2, 4, 8]


In [ ]:
# Map  and reduce

num=[1,5,7,8,9,4]
check=list(filter(lambda n: n%2==0,num))
print(check)
double =list(map(lambda n:n+2,num))
print(double)
sum= reduce(lambda a,b: a+b,double )
print(sum)

[8, 4]
[3, 7, 9, 10, 11, 6]
46


**Decorators**

In [ ]:
# adding extra faetures 
def div (a,b):
  print(a/b)

def may(func):
  def inn(a,b):
    if a<b:
      a,b=b,a
    return func(a,b)
  return inn

div=may(div)
div(2,4) 



2.0


**OOP**

In [ ]:
# class-  blueprint which contains various object
# object- instance

class Person:
   name="Sagar "
   occupation="Intern "
   def info(self):
    print(f"{self.name} is a {self.occupation}" )

a=Person() 
a.name="Kumar"
a.occupation="Student"
# print(a.name,a.occupation)
a.info()


Kumar is a Student


In [ ]:
# using __init__ constructor

class Person:
  def __init__(self, name,occupation):
    self.name=name
    self.occupation=occupation

  def info(self):
    print("Person :",name,"occupation:",occupation)

a=Person('Sagar','Intern') 
a.info()


Person : Sagar occupation: Intern


**Constructor**

In [ ]:
# !pwd
# constructor allocate the memory or size of object
# self work as a pointer

class Person:
  def __init__(self):
    self.name="sagar"
    self.occupation="Intern"

  def update(self):
    self.occupation="Student"
a=Person() 
b=Person() 

a.name="Alan"
a.occupaation='Worker'

a.update()
print(a.name)
print(b.name)

Alan
sagar


In [ ]:
# Types of vairable
class car:

  # color = matalic black # class instance
    def __init__(self):
        self.mil=40
        self.brand="Audi"
a=car()
b=car()

a.mil=50 #instance variable

print(a.brand,a.mil)
print(b.brand,b.mil)


Audi 50
Audi 40


In [ ]:
# types of Method

#  instance method
class Student:
    def __init__(self,m1,m2,m3):
      self.m1=m1
      self.m2=m2
      self.m3=m3

    def avg(self):  # instance method
          return(self.m1 + self.m2 + self.m3)/3

    def get_m1(self): # geters as accessors Method
      return self.m1

    def set_m1(self,value): # seters as mutator Method
      return self.m1=value

s1=Student(89,57,99)
s2=Student(25,30,36)
s1.avg()

81.66666666666667

In [ ]:
# inner class

class Student: # outer class
  def __init__(self,name,rollno):
    self.name=name
    self.rollno=rollno
    self.lap=self.Laptop()

  def show(self):
    print(self.name,self.rollno)
  
  class  Laptop: #inner class 
        def __init__(self):
          self.brand="HP_vitctus "
          self.graphics="Nvidia"

        def show(self):
            print(self.brand,self.graphics)

s1=Student("sagar",33,)
s1.show()

lap1=Student.Laptop()
lap1.show()
       

sagar 33
HP_vitctus  Nvidia


**Inheritance**

In [ ]:
class A: # super class
  def feature1(self):
    print("Feature 1")

  def feature2(self):
    print("Feature 2")

class B(A): # Sub class
  def feature3(self):
    print("Feature 3")

  def feature4(self):
    print("Feature 4")

a1=A()
a1.feature1()
b1=B()
b1.feature3()

Feature 1
Feature 3


In [ ]:
# constructor in Inheritance
class A: # super class
  def __init__(self):
     print(" In  A")
  def feature1(self):
    print("Feature 1")

  def feature2(self):
    print("Feature 2")

class B(A): # Sub class
  def __init__(self):
     super().__init__()
     print(" In  B")

  def feature3(self):
    print("Feature 3") 


  def feature4(self):
    print("Feature 4")

a1=B()

# note : MRO method Resolution Order prefers left order first then right 
# left--> right 
#    \    /
#   sub_class 

 In  A
 In  B


**Polymorpishm**

In [ ]:
# Duck Typing
# Dynamic Typing (same object)
class VScode :
   def execute(self):
     print("compiling sucessfully")
     print("Running sucessfully")

class Pycharm():
   def execute(self):
    print("Caught warning ")
    print("compiling sucessfully")
    print("Running sucessfully")       

class Laptop:
  def code(self,ide):
    ide.execute()

ide =Pycharm() 
lap1=Laptop()
lap1.code(ide)

Caught warning 
compiling sucessfully
Running sucessfully


In [ ]:

# Operator overloading
a=98
b=76
# print(a+b)
print(int.__add__(a,b))

a="str"
b="ing"
print(str.__add__(a,b))



174
string


In [ ]:
class Student:
  def __init__(self,m1,m2):
    self.m1=m1
    self.m2=m2

  def __add__(self,other):
     m1=self.m1+other.m1
     m2=self.m2+other.m2
     s3=Student(m1,m2)
     return s3

  def __str__(self):
    # return self.m1,self.m2,
      # return '{} {}'.format(self.m1,self.m2)
      return f"m1: {self.m1}, m2: {self.m2}"

s1=Student(25,28)
s2=Student(85,52)
s3=s1+s2
print(s3.m1)   
print(s3.m2)   
a=8
print(a.__str__())
print(s1.__str__())

110
80
8
m1: 25, m2: 28


In [ ]:
# Method Overloading & Method Overiding 


# Method Overloading 
 # in python we can not create two methods of same name and same parameter in


class Student:
     def __init__(self,m1,m2):
        self.m1=m1
        self.m2=m2

     def sum(self,a=None ,b=None ,c=None):# Default Parameter 
         s=a+b
         return s
s1= Student(6,7)
print(s1.sum(5,9))

# Method Overriding 
class A:
   def show(self):
    print("In A")
class B(A): # B inherits the A
  pass

a1=B()
a1.show()

14
 In A


Abstract Class and Abstract Method

In [ ]:
# by default python doesn't support Abstract class
# application  based uses 
from abc import ABC, abstractmethod
class Computer(ABC):
    @abstractmethod 
    def pr(self):
      pass
class Laptop(Computer):
  def pr(self):
    print("Hurry up,about to End")

class Programmer:
  def work(self):
    print("Programming ")

com1=Laptop()
com1.pr()

prog1=Programmer()
prog1.work()

Hurry up,about to End
Programming 


**Advance** **Topics**

**Exception** **Handling**

In [ ]:
# compile Error 
# logical Error
# Run Time Error
a=int (input("Enter the Number: "))
b=int (input("Enter the Number: "))

try:
  print(a/b)
  c=int (input ("Enter the Number: "))

except ZeroDivisionError as  e:  # can not divide by Zero (Zero Division Error)
  print("Can not divide by Zero \nException is :",e)

except ValueError as e:  # value Error 
  print("Invalid input")    

except Exception as e:  # common Exception which catch the all Error
  print("Warning, something went wrong")    

finally:
  print("operation Done ")

Enter the Number: 18555
Enter the Number: 0
Can not divide by Zero 
Exception is : division by zero
operation Done 


**Multi** **Threading**

In [ ]:
from time import sleep
from threading import *
class Starbucks(Thread): # Thread 1
    def run(self):
      for i in range(5):
          print("Starbucks ")
          sleep(1)

class Subway (Thread): # Thread 2
   def run(self):
      for i in range(5):
          print("Subway  ")
          sleep(1)

f1=Starbucks()
f2=Subway()


f1.start()
sleep(0.2)
f2.start()
f1.join()
f2.join()

Starbucks 
Subway  
Starbucks 
Subway  
Starbucks 
Subway  
Starbucks 
Subway  
Starbucks 
Subway  


**File** **Handling**

In [ ]:
# Writing in file
file_path = '/content/drive/MyDrive/python.txt'

with open(file_path, 'w') as file:
    file.write("This is some example text.")


In [ ]:
# Reading from the file
file_path = '/content/drive/MyDrive/python.txt'

with open(file_path, 'r') as file:
    content = file.read()
    print(content)


This is some example text.
